<?xml version="1.0"?>
<package format="3">
  <name>lerobot_native</name>
  <version>0.1.0</version>
  <description>C++ LeRobot native application and mlink device wrapper.</description>
  <maintainer email="dev@spacemit.com">Spacemit Robotics</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>cmake</buildtool_depend>
  <depend>mlink_device</depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
